name: estate360Security
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: any
  stacked_services: ^1.0.0
  stacked: ^3.2.0
  image_picker: ^1.1.2
  dio: ^4.0.6
  sembast: ^3.4.3+1
  path_provider: ^2.1.1
  pretty_dio_logger: ^1.1.1
  logger: ^1.4.0
  lottie: any
  smooth_page_indicator: ^1.1.0
  animate_do: ^3.1.2
  intl_phone_field: ^3.0.0
  google_fonts: ^6.2.1
  pin_code_fields: ^8.0.1
  dropdown_button2: ^2.3.9
  time_range_picker: ^2.3.0
  flutter_picker: ^2.1.0
  time_picker_spinner: any
  date_picker_plus: ^3.0.2
  intl: ^0.18.1
  #share_plus: ^7.2.1
  dots_indicator: ^3.0.0
  qr_code_scanner: ^1.0.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  url_launcher: ^6.1.13
  device_info_plus: ^9.1.2
  flutter_timezone: ^1.0.8
  package_info_plus: ^5.0.1
  async: ^2.11.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.2
  firebase_in_app_messaging: ^0.7.4+8
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.18


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1


  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/svg_icons/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/escurecopy.png"
