name: bitSave
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: '>=3.6.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: any
  rxdart: ^0.28.0
  stacked_services: ^1.0.0
  stacked: ^3.2.0
  dio: ^4.0.6
  logger: ^1.4.0
  sembast: ^3.4.3+1
  pretty_dio_logger: ^1.1.1
  lottie: any
  smooth_page_indicator: ^1.1.0
  animate_do: ^4.2.0
  intl_phone_field: ^3.0.0
  google_fonts: ^6.2.1
  pin_code_fields: ^8.0.1
  dropdown_button2: ^2.3.9
  time_range_picker: ^2.3.0
  flutter_picker: ^2.1.0
  time_picker_spinner: any
  date_picker_plus: ^4.2.0
  intl: ^0.20.2
  #share_plus: ^7.2.1
  dots_indicator: ^4.0.1
  qr_flutter: ^4.1.0
  #qr_code_scanner: ^1.0.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  url_launcher: ^6.1.13
  device_info_plus: ^9.1.2
  package_info_plus: ^8.0.2
  async: ^2.11.0
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  firebase_in_app_messaging: ^0.9.0+2
  firebase_analytics: ^12.0.2
  firebase_crashlytics: ^5.0.2
  flutter_breez_liquid:
    git:
      url: https://github.com/breez/breez-sdk-liquid-flutter
      ref: v0.8.3
  flutter_secure_storage: ^9.2.2
  bip39: ^1.0.6



flutter_rust_bridge: ^2.9.0
flutter_local_notifications: ^17.2.2
flutter_plugin_android_lifecycle: ^2.0.22





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.2.8

flutter_native_splash:
  color: "#432E9D"
  android: true
  ios: true
  web: false
  image: "assets/images/bitsavelogo.png"
  fullscreen: true


dependency_overrides:
  win32: ^5.14.0

  path_provider: ^2.1.5
  path_provider_android: ^2.2.9
  path_provider_foundation: ^2.4.0

  image_picker: ^1.1.2
  image_picker_android: ^0.8.12+12
  image_picker_ios: ^0.8.9

  flutter_local_notifications: ^17.2.2
  flutter_timezone: ^2.1.0

   # Ensures device info and package info stay modern
  device_info_plus: ^9.1.2
  package_info_plus: ^8.0.2


  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/bitsaveicon.png"
  android_adaptive_icon:
    foreground_image: "assets/images/bitsaveicon.png"
    background_color: "#000000"
