// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEdWqhUMwEkUdFgxdyTwzUN0wXaAwBxoE',
    appId: '1:264595421239:android:f8cda7b0ebfc4c1cb5a7b2',
    messagingSenderId: '264595421239',
    projectId: 'estate360-ac62d',
    storageBucket: 'estate360-ac62d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe5vzKTgeSROs8wOEMM1kDcFdz_HvI6Ho',
    appId: '1:264595421239:ios:ef35d5bc09968df5b5a7b2',
    messagingSenderId: '264595421239',
    projectId: 'estate360-ac62d',
    storageBucket: 'estate360-ac62d.firebasestorage.app',
    iosBundleId: 'com.echobitstech.estate360Security',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzfRdsczdZ4YlnWvmqwU7ltvFElwGf5sI',
    appId: '1:264595421239:web:ef5a342b8ff97557b5a7b2',
    messagingSenderId: '264595421239',
    projectId: 'estate360-ac62d',
    authDomain: 'estate360-ac62d.firebaseapp.com',
    storageBucket: 'estate360-ac62d.firebasestorage.app',
    measurementId: 'G-F8P9RDWSGY',
  );

}